/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package WDM;

import java.io.File;
import java.util.concurrent.TimeUnit;

import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.chrome.ChromeOptions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;

import io.github.bonigarcia.wdm.WebDriverManager;

public class App {


    public static ChromeDriver createDriver() {
       //TODO : INITIALIZE WEB DRIVER USING WDM

       ChromeOptions options = new ChromeOptions();
        options.addArguments("--headless", "--window-size=1920,1200");

       WebDriverManager.chromedriver().setup();
       ChromeDriver driver = new ChromeDriver(options);
        driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
        return driver;
    }

    public static void verifySearchBox(ChromeDriver driver)
    {
        //TODO: Validate the presence of search box 
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");

        WebDriverWait wait = new WebDriverWait(driver, 10);

        wait.until(ExpectedConditions.presenceOfElementLocated(By.xpath("(//input)[1]")));
		WebElement searchBox = driver.findElement(By.xpath("(//input)[1]"));

        if (searchBox.isDisplayed()){
            System.out.println("Search Box displayed");
        } else {
            System.out.println("Search box is not displayed");
        }
    }
 
 

    // public static void main(String[] args) {
    //     ChromeDriver driver = createDriver();

    //     System.out.println("donloaded path of driver : "+ WebDriverManager.chromedriver().getDownloadedDriverPath());
    //     System.out.println("downloaded driver version : "+ WebDriverManager.chromedriver().getDownloadedDriverVersion());
    //     System.out.println("get browser path : "+ WebDriverManager.chromedriver().getBrowserPath());

    //     try{
    //     verifySearchBox(driver);
    //     }catch(Exception e){
    //         System.out.println("Exception Occured "+ e.getMessage());
    //     }finally{
    //     driver.quit();}
    // }

    public static void takeScreenshot(WebDriver driver, String screenshotType, String Description) {
        try {
            File theDir = new File("/screenshots");
            if (!theDir.exists()) {
                theDir.mkdirs();
            }
            String timestamp = String.valueOf(java.time.LocalDateTime.now());
            String fileName = String.format("screenshot_%s_%s_%s.png", timestamp, screenshotType, Description);
            System.out.println("filepath : "+ fileName);
            fileName = fileName.replace(":", "");
            TakesScreenshot scrShot = ((TakesScreenshot) driver);
            File SrcFile = scrShot.getScreenshotAs(OutputType.FILE);
            File DestFile = new File("screenshots/" + fileName);
            FileUtils.copyFile(SrcFile, DestFile);
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    public static void LaunchQKARTTakeScreenshot(WebDriver driver) {
        driver.get("https://crio-qkart-frontend-qa.vercel.app/");
        takeScreenshot(driver, "QKART_Home_Page", "Screenshot_Of_QKART_Home");
    }

    public static void main(String[] args) {
        WebDriver driver = createDriver();
        try {
            LaunchQKARTTakeScreenshot(driver);
        } catch (Exception e) {
            System.out.println("Exception Occured " + e.getMessage());
        } finally {
            driver.quit();
        }
    }
}
